import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

/**
 * Deliberately narrow, for the same reason the backend's ruff config is (see
 * [tool.ruff] in the API repo's pyproject.toml): the point is to catch new
 * mistakes mechanically, not to reformat a working codebase. A first run that
 * demands three hundred edits is a linter people turn off, and a linter people
 * turn off catches nothing at all.
 *
 * So this starts from `next/core-web-vitals` — the rules that catch real Next
 * bugs, like a client-only hook in a server component or an <img> that will
 * quietly cost a user their bandwidth — and switches off the stylistic ones
 * this codebase has never followed. Each of those is listed with why, so
 * turning one back on later is a decision rather than an archaeology exercise.
 */
export default [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'out/**',
      'next-env.d.ts',
      // Generated by shadcn/ui, not written here. Linting vendored components
      // produces a list of complaints nobody is going to act on.
      'src/components/ui/**',
    ],
  },
  {
    // Tailwind's plugins are loaded with require() because that is what the
    // Tailwind config format expects. Nothing here ships to the browser.
    files: ['tailwind.config.ts', '*.config.{js,mjs,ts}'],
    rules: { '@typescript-eslint/no-require-imports': 'off' },
  },
  {
    rules: {
      // Typography, not correctness: an apostrophe in JSX prose renders
      // exactly as intended. Fifteen of these on the first run, every one of
      // them prose somebody wrote deliberately, and none of them a bug worth
      // failing a build over.
      'react/no-unescaped-entities': 'off',
      // `any` appears in every catch block in this codebase (`catch (error:
      // any)`) because that is the shape the fetch wrapper throws. Making this
      // an error would flag ~every mutation handler in the app for a pattern
      // that is deliberate and consistent. Warn, so new ones are visible
      // without the existing ones failing the build.
      '@typescript-eslint/no-explicit-any': 'warn',
      // Same reasoning: unused vars are worth seeing, not worth blocking on,
      // and the underscore convention already marks the intentional ones.
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
];
