
import type { Metadata, Viewport } from 'next';
import { Open_Sans, Roboto_Flex } from 'next/font/google';
import './globals.css';
import { Providers } from './providers';

const bodyFont = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '600'],
  variable: '--font-body',
  display: 'swap',
});

const headlineFont = Roboto_Flex({
  subsets: ['latin'],
  weight: ['600', '700'],
  variable: '--font-headline',
  display: 'swap',
});

export const metadata: Metadata = {
  title: {
    default: 'Sarmaya Prototype',
    template: '%s | Sarmaya Prototype',
  },
  // What shows under the title in search results and link previews. It said
  // "Generated by Firebase Studio", left over from the scaffold this started
  // from, so every shared link described the tool, not the product.
  description:
    'Invoice and accounts-payable automation, with governed approvals and a '
    + 'tamper-evident audit trail.',
};

export const viewport: Viewport = {
  themeColor: '#020817',
  colorScheme: 'dark',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body className={`${bodyFont.variable} ${headlineFont.variable} font-body antialiased`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
